### PR TITLE
General Refactor

### PR DESCRIPTION
**Pull request by rhenter**
Since it is no longer possible to use the google API for free, I advise you to change the name of your repository.

This PR comes with the following refactors:
  - [x] Remove urllib to use requests
  - [x]  Refactor methods names removing google from then
  - [x]  Apply PEP8
  - [x] Change contructor to keep it the code simple

PS: If you agree we can add multiple providers later to use different translators, even the paid ones.

### CODE REVIEW

**Comment by terryyin** [comment]
Thanks. will do.

But do you know why the travis ci says: "ImportError: No module named 'requests'"?

**Comment by rhenter** [comment]
I will fix the tests tomorrow. Please tell me if you don't like of something.

**Comment by terryyin** [comment]
Looks good to me:-)

**Comment by rhenter** [comment]
Now I did a general refactor. 

 - [x] Add a module folder to use as a library or as a module
   Ex:
```shell
$ python -m translate 
usage: __main__.py [-h] [-t TO_LANG] [-f FROM_LANG] text [text ...]
__main__.py: error: the following arguments are required: text
```
 - [x] Add fix translate client to make translations of multiples args
  ```shell
  $ translate-cli --f en --t pt-BR the book is on the table
  O livro esta em cima da mesa
  ```
 - [x] Add new make file to get easier make build, tests or update requirements file.
   Ex: `make build` or `make pip-compile` (update requirements)
 - [x] Add pyenv instead of unnitest to get flexbility and increase converage 
  Ex: https://gist.github.com/rhenter/f3cc6326d9eb33aa84c55c5d74f8da9f
 - [x] Add VCR to mock API requests with exception of command line testes that using subprocess command
 - [X] Add improvement to unicode errors on python 2.7
 - [x] Add pre-commit to get sure that you are following PEP8 correctly
 Ex: https://gist.github.com/rhenter/c2406331335fcc317ac59efbf2b94e87
 - [X] Update config files

**Comment by rhenter** [comment]
@terryyin after this PR, we can change to let the user choice her provider even if wore a paid provider, like google, bing, azure, etc...

I was thinking in create a project like this, but I did prefer working with you.

**Comment by rhenter** [comment]
@terryyin Did you see this PR? Do you want me to change anything?

**Comment by terryyin** [comment]
Hi @rhenter thanks for the PR.

**Comment by terryyin** [comment]
I like the code very much. Some of the test will fail in the near future as the translation changes over time. But I guess that shouldn't be a big problem.

**Comment by terryyin** [comment]
published. Had to do a minor change as PyPI doesn't know about Python 3.6 yet.

**Comment by terryyin** [comment]
Hi @rhenter, BTW I wouldn't mind if you republish it on PyPi under the name python-translate (if it's available).

**Comment by rhenter** [comment]
@terryyin about the tests fail in the future, only the translation client wasn’t mock with VCR, the others test works even offline. And about to republish, I think than two is better than one. That was the reason I did prefer to help your project instead of create a another project that make the same thing.

**Pull request merged**
